litellm_settings:
  drop_params: true
  num_retries: 3
  routing_strategy: simple-shuffle
model_list:
- litellm_params:
    api_base: http://10.56.9.8:38465/v1
    drop_params: true
    model: hosted_vllm/Qwen/Qwen3-4B-Instruct-2507
  model_info:
    id: verl-replica-0
    replica_rank: 0
  model_name: vllm/Qwen/Qwen3-4B-Instruct-2507
- litellm_params:
    api_base: http://10.56.9.8:43901/v1
    drop_params: true
    model: hosted_vllm/Qwen/Qwen3-4B-Instruct-2507
  model_info:
    id: verl-replica-1
    replica_rank: 1
  model_name: vllm/Qwen/Qwen3-4B-Instruct-2507
- litellm_params:
    api_base: http://10.56.9.8:38869/v1
    drop_params: true
    model: hosted_vllm/Qwen/Qwen3-4B-Instruct-2507
  model_info:
    id: verl-replica-2
    replica_rank: 2
  model_name: vllm/Qwen/Qwen3-4B-Instruct-2507
- litellm_params:
    api_base: http://10.56.9.8:45135/v1
    drop_params: true
    model: hosted_vllm/Qwen/Qwen3-4B-Instruct-2507
  model_info:
    id: verl-replica-3
    replica_rank: 3
  model_name: vllm/Qwen/Qwen3-4B-Instruct-2507
- litellm_params:
    api_base: http://10.56.9.8:33549/v1
    drop_params: true
    model: hosted_vllm/Qwen/Qwen3-4B-Instruct-2507
  model_info:
    id: verl-replica-4
    replica_rank: 4
  model_name: vllm/Qwen/Qwen3-4B-Instruct-2507
- litellm_params:
    api_base: http://10.56.9.8:37873/v1
    drop_params: true
    model: hosted_vllm/Qwen/Qwen3-4B-Instruct-2507
  model_info:
    id: verl-replica-5
    replica_rank: 5
  model_name: vllm/Qwen/Qwen3-4B-Instruct-2507
- litellm_params:
    api_base: http://10.56.9.8:46099/v1
    drop_params: true
    model: hosted_vllm/Qwen/Qwen3-4B-Instruct-2507
  model_info:
    id: verl-replica-6
    replica_rank: 6
  model_name: vllm/Qwen/Qwen3-4B-Instruct-2507
- litellm_params:
    api_base: http://10.56.9.8:40815/v1
    drop_params: true
    model: hosted_vllm/Qwen/Qwen3-4B-Instruct-2507
  model_info:
    id: verl-replica-7
    replica_rank: 7
  model_name: vllm/Qwen/Qwen3-4B-Instruct-2507
